name: Push and PR workflow

on:
  push:
  pull_request:
env:
  repository: https://github.com/powerapi-ng/virtualwatts-formula
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y libvirt-dev procps
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install flake8 pylint
          pip install .
      - name: Test with pytest
        run: |
          . venv/bin/activate
          python setup.py test
      - name: Lint with flake8
        run: |
          . venv/bin/activate
          flake8 virtualwatts
      - name: Lint with pylint
        run: |
          . venv/bin/activate
          pylint virtuallwatts
