name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8
    - name: Analysing the code with pylint
      run: |
        pylint virtualwatts
        flake8 virtualwatts

    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0
